In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt  # 추가한 부분

import matplotlib as mpl
plt.rc('font', family='NanumBarunGothic') 

# 폰트 변환
# Windows
mpl.rc("font", family='Malgun Gothic')

In [2]:
ctiy_df = pd.read_csv('ctiy_data.csv')
ctiy_df

,jb,ahr,sp,ap,grdp,gj,go,cgo,sup,pits,pses,hos,psap,pls,ppsp,target
0,88,18,5,10,4736,54,84,62,4,21,21,16,26,28,26,1
1,78,33,5,29,4769,61,90,77,4,23,14,13,16,26,14,1
2,64,10,13,20,1574,65,79,98,5,11,15,15,26,23,25,1
3,92,21,13,26,4261,75,66,74,2,26,13,10,29,18,15,1
4,57,17,8,17,2148,75,98,82,4,23,28,14,18,17,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,64,32,7,28,2008,61,57,70,4,24,29,15,26,24,16,1
96,94,37,7,24,3141,98,90,97,5,20,24,10,19,21,23,1
97,50,34,7,11,2773,62,88,55,0,17,24,26,23,25,20,1
98,74,16,8,11,1957,72,50,77,4,28,10,20,26,28,22,1
99,56,39,12,28,4059,74,52,66,8,22,29,27,27,17,11,1